version: '3'

services:
  mysql:
    image: mysql-db
    restart: always
    ports:
      - 3307:3306
    depends_on:
      - mq

  mq:
    image: ibm-mq
    ports:
      - "1414:1414"
    environment:
        - LICENSE=accept
        - MQ_QMGR_NAME=MQA01
    volumes:
        - mqseries-volume:/mnt/mqm
    stdin_open: true
    tty: true
    restart: always

  tomcat:
    image: tomcat
    ports:
      - "8080:8080"
    volumes:
     - ./helloworld.html:/usr/local/tomcat/webapps/helloworld.html